include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    omit_local_variable_types: ignore

linter:
  rules:
    - camel_case_types
