name: photopuzzle
description: a project about puzzle

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # https://pub.dev/packages/camera#-installing-tab-
  camera:
  path_provider:
  path:
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.16.1
  # https://pub.dev/packages/cloud_firestore#-installing-tab-
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.1.4
  # https://pub.flutter-io.cn/packages/image_picker#-installing-tab-
  image_picker: ^0.6.7+4
  # https://pub.dev/packages/flutter_image_compress#why-dont-you-use-dart-to-do-it
  flutter_image_compress: ^0.7.0
  # https://pub.dev/packages/random_string#-installing-tab-
  random_string: ^2.1.0
  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^1.1.3
  # https://flutter.dev/docs/cookbook/persistence/sqlite
  sqflite:
  # https://pub:dev/packages/stop_watch_timer:
  stop_watch_timer:
  # https://pub:dev/packages/vibration:
  vibrate: ^0.0.4
  # https://pub.dev/packages/fab_circular_menu
  fab_circular_menu: ^1.0.0
  # https://pub.dev/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: "^0.3.0"
  # https://pub.dev/packages/animations#-installing-tab-
  animations: ^1.1.1
  # https://pub.dev/packages/provider#-installing-tab-
  provider: ^4.3.1



dev_dependencies:
  # https://pub.dev/packages/floor
  floor_generator: ^0.13.0
  build_runner: ^1.7.3
  # over
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/bg/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
